version: "3.9"

networks:
  campus-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.4
    container_name: campus_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: campus_smartphone_addiction
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"   # expose to host (optional if only containers need access)
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - campus-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
